name: Deploy to Infomaniak
on:
  workflow_dispatch:

jobs:
  web-deploy:
    name: Manual Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v5

      - name: Installer Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'npm'

      - name: Installer les dépendances
        run: npm ci

      - name: Générer les Audios
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: npm run gen:audio

      - name: Build
        run: npm run build

      - name: Envoyer sur Infomaniak (FTP)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/
          server-dir: /
          dangerous-clean-slate: true
          protocol: ftps
          exclude: |
            **/.git*
            **/.git*/**
            node_modules/**
            .htaccess
            .user.ini
            .infomaniak-maintenance.html
