name: Deploy to Infomaniak
on:
  workflow_dispatch:

jobs:
  web-deploy:
    name: Manual Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v5

      - name: Installer Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: 'npm'

      - name: Installer les dépendances
        run: npm ci

      - name: Restaurer le cache Audio
        uses: actions/cache@v4
        id: cache-audio
        with:
          path: public/audio
          key: audio-${{ runner.os }}-${{ hashFiles('public/markdown/**/*.md') }}
          restore-keys: |
            audio-${{ runner.os }}-

      - name: Générer les Audios manquants
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: npm run gen:audio

      - name: Générer l'index du contenu
        run: npm run gen:content

      - name: Générer les Quiz
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: npm run gen:quiz

      - name: Build
        run: npm run build

      - name: Envoyer sur Infomaniak (FTP)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/
          server-dir: /
          protocol: ftps
          exclude: |
            **/.git*
            **/.git*/**
            node_modules/**
