name: Generate Audio from Markdown

on:
  push:
    paths:
      - 'public/markdown/**.md'
      - 'generate-audio.js'

permissions:
  contents: write

jobs:
  build-and-generate:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v5

      - name: Installer Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'npm'

      - name: Installer les dépendances
        run: npm ci

      - name: Générer les fichiers Audio
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: npm run gen:audio

      - name: Sauvegarder les changements (Commit & Push)
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Auto-generate audio files'
          file_pattern: 'public/audio/*.mp3'
